// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topology.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	topology.proto

It has these top-level messages:
	IPAdress
	Interface
	Tap
	Bridge
	Topology
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IPAdress struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *IPAdress) Reset()                    { *m = IPAdress{} }
func (m *IPAdress) String() string            { return proto.CompactTextString(m) }
func (*IPAdress) ProtoMessage()               {}
func (*IPAdress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IPAdress) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Interface struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Interface) Reset()                    { *m = Interface{} }
func (m *Interface) String() string            { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()               {}
func (*Interface) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Tap struct {
	Name       string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mac        string      `protobuf:"bytes,2,opt,name=mac" json:"mac,omitempty"`
	IpAdresses []*IPAdress `protobuf:"bytes,3,rep,name=ip_adresses,json=ipAdresses" json:"ip_adresses,omitempty"`
}

func (m *Tap) Reset()                    { *m = Tap{} }
func (m *Tap) String() string            { return proto.CompactTextString(m) }
func (*Tap) ProtoMessage()               {}
func (*Tap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Tap) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tap) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Tap) GetIpAdresses() []*IPAdress {
	if m != nil {
		return m.IpAdresses
	}
	return nil
}

type Bridge struct {
	Name       string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Interfaces []*Interface `protobuf:"bytes,2,rep,name=interfaces" json:"interfaces,omitempty"`
}

func (m *Bridge) Reset()                    { *m = Bridge{} }
func (m *Bridge) String() string            { return proto.CompactTextString(m) }
func (*Bridge) ProtoMessage()               {}
func (*Bridge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Bridge) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bridge) GetInterfaces() []*Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type Topology struct {
	Bridge *Bridge `protobuf:"bytes,1,opt,name=bridge" json:"bridge,omitempty"`
	Taps   []*Tap  `protobuf:"bytes,2,rep,name=taps" json:"taps,omitempty"`
}

func (m *Topology) Reset()                    { *m = Topology{} }
func (m *Topology) String() string            { return proto.CompactTextString(m) }
func (*Topology) ProtoMessage()               {}
func (*Topology) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Topology) GetBridge() *Bridge {
	if m != nil {
		return m.Bridge
	}
	return nil
}

func (m *Topology) GetTaps() []*Tap {
	if m != nil {
		return m.Taps
	}
	return nil
}

func init() {
	proto.RegisterType((*IPAdress)(nil), "model.IPAdress")
	proto.RegisterType((*Interface)(nil), "model.Interface")
	proto.RegisterType((*Tap)(nil), "model.Tap")
	proto.RegisterType((*Bridge)(nil), "model.Bridge")
	proto.RegisterType((*Topology)(nil), "model.Topology")
}

func init() { proto.RegisterFile("topology.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x69, 0x52, 0x43, 0xfb, 0x82, 0xb5, 0xcc, 0x29, 0x78, 0xd0, 0xb2, 0x20, 0xf4, 0x14,
	0x4a, 0xfd, 0x05, 0xf5, 0xd6, 0x8b, 0xe8, 0x92, 0xab, 0xc8, 0xb6, 0x59, 0xcb, 0x42, 0xd3, 0x1d,
	0xb2, 0x7b, 0xf1, 0xdf, 0x8b, 0xe3, 0x2e, 0x78, 0xe8, 0x6d, 0x98, 0xf7, 0xe6, 0x7b, 0x8f, 0xc1,
	0x22, 0x7a, 0xf6, 0x67, 0x7f, 0xfa, 0x6e, 0x79, 0xf4, 0xd1, 0xd3, 0xcd, 0xe0, 0x7b, 0x7b, 0x56,
	0xf7, 0x98, 0xed, 0xdf, 0x76, 0xfd, 0x68, 0x43, 0xa0, 0x05, 0x0a, 0xc7, 0xcd, 0x64, 0x35, 0x59,
	0xcf, 0x75, 0xe1, 0x58, 0x3d, 0x62, 0xbe, 0xbf, 0x44, 0x3b, 0x7e, 0x99, 0xa3, 0x25, 0xc2, 0xf4,
	0x62, 0x06, 0x9b, 0x64, 0x99, 0xd5, 0x07, 0xca, 0xce, 0xf0, 0x35, 0x89, 0x96, 0x28, 0x07, 0x73,
	0x6c, 0x0a, 0x59, 0xfd, 0x8e, 0xb4, 0x41, 0xed, 0xf8, 0xd3, 0x48, 0x94, 0x0d, 0x4d, 0xb9, 0x2a,
	0xd7, 0xf5, 0xf6, 0xae, 0x95, 0x1a, 0x6d, 0xee, 0xa0, 0xe1, 0x78, 0x97, 0x2c, 0xea, 0x15, 0xd5,
	0xcb, 0xe8, 0xfa, 0xd3, 0xd5, 0x70, 0xda, 0x00, 0x2e, 0xb7, 0x0b, 0x4d, 0x21, 0xb8, 0x65, 0xc6,
	0x65, 0x41, 0xff, 0xf3, 0xa8, 0x77, 0xcc, 0xba, 0xf4, 0x04, 0x7a, 0x42, 0x75, 0x10, 0xb6, 0x30,
	0xeb, 0xed, 0x6d, 0xba, 0xfc, 0x0b, 0xd4, 0x49, 0xa4, 0x07, 0x4c, 0xa3, 0xe1, 0x8c, 0x47, 0x32,
	0x75, 0x86, 0xb5, 0xec, 0x0f, 0x95, 0x3c, 0xf3, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xeb,
	0x91, 0xe1, 0x5e, 0x01, 0x00, 0x00,
}
